// =============================================================================
// BATTLECRAPS — BOSS RULE: DISABLE_CREW — "The Tariff" (Mme. Le Prix, F3)
//
// Mme. Le Prix no longer silences the crew — she taxes them. Every additive
// generated by the crew is reduced by additiveTarifPct (35%) before settlement.
// Multipliers and hype ticks are unaffected. The cascade fires normally, so
// crew portraits still animate and cooldowns still tick — the fight stays live.
//
// This creates a floor-specific meta shift: multiplier/hype builds outperform
// additive-heavy builds on F3, the only floor where that is true.
//
// Previously: modifyCascadeOrder returning [] — full cascade suppress.
// Now: modifyAdditives reducing the resulting additives pool by 35%.
// =============================================================================

import type { BossRuleHooks } from './types.js';

export const disableCrewHooks: BossRuleHooks = {
  modifyAdditives(additives, params, _state) {
    if (params.rule !== 'DISABLE_CREW') return additives;
    const taxed = Math.floor(additives * (1 - params.additiveTarifPct) / 100) * 100;
    return Math.max(0, taxed);
  },
};
